# fly.toml app configuration file generated for anonpaper-server on 2023-12-21T22:09:46-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "anonpaper-server"
primary_region = "iad"

[build]

[http_service]
internal_port = 4000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
